/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SituationsRouteImport } from './routes/situations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtSituation_idRouteImport } from './routes/thought.$situation_id'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProofSituation_idThought_idRouteImport } from './routes/proof.$situation_id.$thought_id'

const SituationsRoute = SituationsRouteImport.update({
  id: '/situations',
  path: '/situations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtSituation_idRoute = ThoughtSituation_idRouteImport.update({
  id: '/thought/$situation_id',
  path: '/thought/$situation_id',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofSituation_idThought_idRoute =
  ProofSituation_idThought_idRouteImport.update({
    id: '/proof/$situation_id/$thought_id',
    path: '/proof/$situation_id/$thought_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/situations': typeof SituationsRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/thought/$situation_id': typeof ThoughtSituation_idRoute
  '/proof/$situation_id/$thought_id': typeof ProofSituation_idThought_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/situations': typeof SituationsRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/thought/$situation_id': typeof ThoughtSituation_idRoute
  '/proof/$situation_id/$thought_id': typeof ProofSituation_idThought_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/situations': typeof SituationsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/thought/$situation_id': typeof ThoughtSituation_idRoute
  '/proof/$situation_id/$thought_id': typeof ProofSituation_idThought_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/situations'
    | '/login'
    | '/register'
    | '/thought/$situation_id'
    | '/proof/$situation_id/$thought_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/situations'
    | '/login'
    | '/register'
    | '/thought/$situation_id'
    | '/proof/$situation_id/$thought_id'
  id:
    | '__root__'
    | '/'
    | '/situations'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/thought/$situation_id'
    | '/proof/$situation_id/$thought_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SituationsRoute: typeof SituationsRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  ThoughtSituation_idRoute: typeof ThoughtSituation_idRoute
  ProofSituation_idThought_idRoute: typeof ProofSituation_idThought_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/situations': {
      id: '/situations'
      path: '/situations'
      fullPath: '/situations'
      preLoaderRoute: typeof SituationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thought/$situation_id': {
      id: '/thought/$situation_id'
      path: '/thought/$situation_id'
      fullPath: '/thought/$situation_id'
      preLoaderRoute: typeof ThoughtSituation_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$situation_id/$thought_id': {
      id: '/proof/$situation_id/$thought_id'
      path: '/proof/$situation_id/$thought_id'
      fullPath: '/proof/$situation_id/$thought_id'
      preLoaderRoute: typeof ProofSituation_idThought_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SituationsRoute: SituationsRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  ThoughtSituation_idRoute: ThoughtSituation_idRoute,
  ProofSituation_idThought_idRoute: ProofSituation_idThought_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
